spring.application.name=unify-catalog
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

### Spring Batch ###
# This parameter is for standalone Spring Batch CLI tool applications
spring.batch.job.enabled=false
# Spring Batch can create its own DB tables, but won't by default
spring.batch.jdbc.initialize-schema=ALWAYS

### DB configuration ###
spring.dataSource.url=jdbc:postgresql://localhost:5432/unitest
spring.dataSource.username=unitest
spring.dataSource.password=0000

### Logging ###
logging.level.com.setronica.unify.application.impex.ProductItemValidator=DEBUG
